services:
  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    container_name: logbook_pocketbase
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - ./pocketbase/base/pb_data:/pb/pb_data
    # Run migrations before serving so all collections are created on first boot
    command: sh -c "/pb/pocketbase migrate up && /pb/pocketbase serve --http=0.0.0.0:8080"
