/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as PassResetRouteImport } from './routes/pass-reset'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAircraftRouteImport } from './routes/_authed/aircraft'
import { Route as AuthedAnalysisRouteImport } from './routes/_authed/analysis'
import { Route as AuthedCheckFlightsRouteImport } from './routes/_authed/check-flights'
import { Route as AuthedCurrencyRouteImport } from './routes/_authed/currency'
import { Route as AuthedIacraTotalsRouteImport } from './routes/_authed/iacra-totals'
import { Route as AuthedImportRouteImport } from './routes/_authed/import'
import { Route as AuthedInstructRouteImport } from './routes/_authed/instruct'
import { Route as AuthedPendingFlightsRouteImport } from './routes/_authed/pending-flights'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedStartingTotalsRouteImport } from './routes/_authed/starting-totals'
import { Route as SignTokenRouteImport } from './routes/sign/$token'
import { Route as AuthedLogFlightIndexRouteImport } from './routes/_authed/log-flight.index'
import { Route as AuthedLogFlightFlightIdRouteImport } from './routes/_authed/log-flight.$flightId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const PassResetRoute = PassResetRouteImport.update({
  id: '/pass-reset',
  path: '/pass-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAircraftRoute = AuthedAircraftRouteImport.update({
  id: '/aircraft',
  path: '/aircraft',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnalysisRoute = AuthedAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCheckFlightsRoute = AuthedCheckFlightsRouteImport.update({
  id: '/check-flights',
  path: '/check-flights',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCurrencyRoute = AuthedCurrencyRouteImport.update({
  id: '/currency',
  path: '/currency',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIacraTotalsRoute = AuthedIacraTotalsRouteImport.update({
  id: '/iacra-totals',
  path: '/iacra-totals',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedImportRoute = AuthedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInstructRoute = AuthedInstructRouteImport.update({
  id: '/instruct',
  path: '/instruct',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPendingFlightsRoute = AuthedPendingFlightsRouteImport.update({
  id: '/pending-flights',
  path: '/pending-flights',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStartingTotalsRoute = AuthedStartingTotalsRouteImport.update({
  id: '/starting-totals',
  path: '/starting-totals',
  getParentRoute: () => AuthedRoute,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLogFlightIndexRoute = AuthedLogFlightIndexRouteImport.update({
  id: '/log-flight/',
  path: '/log-flight/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLogFlightFlightIdRoute = AuthedLogFlightFlightIdRouteImport.update({
  id: '/log-flight/$flightId',
  path: '/log-flight/$flightId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/logout': typeof LogoutRoute
  '/pass-reset': typeof PassResetRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/aircraft': typeof AuthedAircraftRoute
  '/analysis': typeof AuthedAnalysisRoute
  '/check-flights': typeof AuthedCheckFlightsRoute
  '/currency': typeof AuthedCurrencyRoute
  '/iacra-totals': typeof AuthedIacraTotalsRoute
  '/import': typeof AuthedImportRoute
  '/instruct': typeof AuthedInstructRoute
  '/pending-flights': typeof AuthedPendingFlightsRoute
  '/profile': typeof AuthedProfileRoute
  '/starting-totals': typeof AuthedStartingTotalsRoute
  '/sign/$token': typeof SignTokenRoute
  '/log-flight/$flightId': typeof AuthedLogFlightFlightIdRoute
  '/log-flight/': typeof AuthedLogFlightIndexRoute
}
export interface FileRoutesByTo {
  '/logout': typeof LogoutRoute
  '/pass-reset': typeof PassResetRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/aircraft': typeof AuthedAircraftRoute
  '/analysis': typeof AuthedAnalysisRoute
  '/check-flights': typeof AuthedCheckFlightsRoute
  '/currency': typeof AuthedCurrencyRoute
  '/iacra-totals': typeof AuthedIacraTotalsRoute
  '/import': typeof AuthedImportRoute
  '/instruct': typeof AuthedInstructRoute
  '/pending-flights': typeof AuthedPendingFlightsRoute
  '/profile': typeof AuthedProfileRoute
  '/starting-totals': typeof AuthedStartingTotalsRoute
  '/sign/$token': typeof SignTokenRoute
  '/': typeof AuthedIndexRoute
  '/log-flight/$flightId': typeof AuthedLogFlightFlightIdRoute
  '/log-flight': typeof AuthedLogFlightIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/logout': typeof LogoutRoute
  '/pass-reset': typeof PassResetRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authed/aircraft': typeof AuthedAircraftRoute
  '/_authed/analysis': typeof AuthedAnalysisRoute
  '/_authed/check-flights': typeof AuthedCheckFlightsRoute
  '/_authed/currency': typeof AuthedCurrencyRoute
  '/_authed/iacra-totals': typeof AuthedIacraTotalsRoute
  '/_authed/import': typeof AuthedImportRoute
  '/_authed/instruct': typeof AuthedInstructRoute
  '/_authed/pending-flights': typeof AuthedPendingFlightsRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/starting-totals': typeof AuthedStartingTotalsRoute
  '/sign/$token': typeof SignTokenRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/log-flight/$flightId': typeof AuthedLogFlightFlightIdRoute
  '/_authed/log-flight/': typeof AuthedLogFlightIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/pass-reset'
    | '/sign-in'
    | '/sign-up'
    | '/aircraft'
    | '/analysis'
    | '/check-flights'
    | '/currency'
    | '/iacra-totals'
    | '/import'
    | '/instruct'
    | '/pending-flights'
    | '/profile'
    | '/starting-totals'
    | '/sign/$token'
    | '/log-flight/$flightId'
    | '/log-flight/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/logout'
    | '/pass-reset'
    | '/sign-in'
    | '/sign-up'
    | '/aircraft'
    | '/analysis'
    | '/check-flights'
    | '/currency'
    | '/iacra-totals'
    | '/import'
    | '/instruct'
    | '/pending-flights'
    | '/profile'
    | '/starting-totals'
    | '/sign/$token'
    | '/'
    | '/log-flight/$flightId'
    | '/log-flight'
  id:
    | '__root__'
    | '/_authed'
    | '/logout'
    | '/pass-reset'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/aircraft'
    | '/_authed/analysis'
    | '/_authed/check-flights'
    | '/_authed/currency'
    | '/_authed/iacra-totals'
    | '/_authed/import'
    | '/_authed/instruct'
    | '/_authed/pending-flights'
    | '/_authed/profile'
    | '/_authed/starting-totals'
    | '/sign/$token'
    | '/_authed/'
    | '/_authed/log-flight/$flightId'
    | '/_authed/log-flight/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  PassResetRoute: typeof PassResetRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SignTokenRoute: typeof SignTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pass-reset': {
      id: '/pass-reset'
      path: '/pass-reset'
      fullPath: '/pass-reset'
      preLoaderRoute: typeof PassResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/aircraft': {
      id: '/_authed/aircraft'
      path: '/aircraft'
      fullPath: '/aircraft'
      preLoaderRoute: typeof AuthedAircraftRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/analysis': {
      id: '/_authed/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AuthedAnalysisRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/check-flights': {
      id: '/_authed/check-flights'
      path: '/check-flights'
      fullPath: '/check-flights'
      preLoaderRoute: typeof AuthedCheckFlightsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/currency': {
      id: '/_authed/currency'
      path: '/currency'
      fullPath: '/currency'
      preLoaderRoute: typeof AuthedCurrencyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/iacra-totals': {
      id: '/_authed/iacra-totals'
      path: '/iacra-totals'
      fullPath: '/iacra-totals'
      preLoaderRoute: typeof AuthedIacraTotalsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/import': {
      id: '/_authed/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthedImportRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/instruct': {
      id: '/_authed/instruct'
      path: '/instruct'
      fullPath: '/instruct'
      preLoaderRoute: typeof AuthedInstructRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pending-flights': {
      id: '/_authed/pending-flights'
      path: '/pending-flights'
      fullPath: '/pending-flights'
      preLoaderRoute: typeof AuthedPendingFlightsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/starting-totals': {
      id: '/_authed/starting-totals'
      path: '/starting-totals'
      fullPath: '/starting-totals'
      preLoaderRoute: typeof AuthedStartingTotalsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/log-flight/': {
      id: '/_authed/log-flight/'
      path: '/log-flight'
      fullPath: '/log-flight/'
      preLoaderRoute: typeof AuthedLogFlightIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/log-flight/$flightId': {
      id: '/_authed/log-flight/$flightId'
      path: '/log-flight/$flightId'
      fullPath: '/log-flight/$flightId'
      preLoaderRoute: typeof AuthedLogFlightFlightIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAircraftRoute: typeof AuthedAircraftRoute
  AuthedAnalysisRoute: typeof AuthedAnalysisRoute
  AuthedCheckFlightsRoute: typeof AuthedCheckFlightsRoute
  AuthedCurrencyRoute: typeof AuthedCurrencyRoute
  AuthedIacraTotalsRoute: typeof AuthedIacraTotalsRoute
  AuthedImportRoute: typeof AuthedImportRoute
  AuthedInstructRoute: typeof AuthedInstructRoute
  AuthedPendingFlightsRoute: typeof AuthedPendingFlightsRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedStartingTotalsRoute: typeof AuthedStartingTotalsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedLogFlightFlightIdRoute: typeof AuthedLogFlightFlightIdRoute
  AuthedLogFlightIndexRoute: typeof AuthedLogFlightIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAircraftRoute: AuthedAircraftRoute,
  AuthedAnalysisRoute: AuthedAnalysisRoute,
  AuthedCheckFlightsRoute: AuthedCheckFlightsRoute,
  AuthedCurrencyRoute: AuthedCurrencyRoute,
  AuthedIacraTotalsRoute: AuthedIacraTotalsRoute,
  AuthedImportRoute: AuthedImportRoute,
  AuthedInstructRoute: AuthedInstructRoute,
  AuthedPendingFlightsRoute: AuthedPendingFlightsRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedStartingTotalsRoute: AuthedStartingTotalsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedLogFlightFlightIdRoute: AuthedLogFlightFlightIdRoute,
  AuthedLogFlightIndexRoute: AuthedLogFlightIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LogoutRoute: LogoutRoute,
  PassResetRoute: PassResetRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SignTokenRoute: SignTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
